server:
  port: 8088
 
spring:
  datasource:
    url: jdbc:oracle:thin:@10.100.8.174:3201/EDSQA01
    username: RIEP_USER
    password: RI3P_U$Er
    driverClassName: oracle.jdbc.OracleDriver
    
  
   
 
management:
  endpoints:
    web:
      base-path: /mscmov-catalogos-riep/actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full

springdoc:
  api-docs:
    path: /mscmov-catalogos-riep/docs/api-docs
    enabled: true
  swagger-ui:
    path: /mscmov-catalogos-riep/docs/swagger-ui.html
    enabled: true

