package mx.gob.imss.mscmovcatalogosriep.integration.contants;

public class SQLConstants {

	private SQLConstants() {}
	
	public static final String QS_CONSULTA_ID_MUNICIPIO = ""
			+ " SELECT mun.ID_MUNICIPIO, mun.CVE_MUNICIPIO,mun.NOM_MUNICIPIO "
			+ " FROM  REIPC_MUNICIPIO mun "
			+ " WHERE mun.ID_MUNICIPIO=? "
			+ " AND mun.STP_BAJA IS NULL";
	
	public static final String QS_CONSULTA_MUNICIPIO_ID_ENTIDAD = ""
			+ "SELECT a.ID_MUNICIPIO, a.CVE_MUNICIPIO, a.NOM_MUNICIPIO   "
            + "FROM REIPC_MUNICIPIO a "
			+ "WHERE a.ID_ENTIDAD_FEDERATIVA = ? "
			+ "AND a.STP_BAJA IS NULL ";

	public static final String QS_CONSULTA_MUNICIPIOS = ""
			+ "SELECT mun.ID_MUNICIPIO,mun.CVE_MUNICIPIO,mun.NOM_MUNICIPIO "
			+ "FROM  REIPC_MUNICIPIO mun "
			+ "WHERE mun.STP_BAJA IS NULL "
			+ "ORDER BY mun.ID_ENTIDAD_FEDERATIVA,mun.CVE_MUNICIPIO";
	
	public static final String QS_CONSULTA_ID_ENTIDAD_FEDERATIVA = ""

			+ "SELECT enf.ID_ENTIDAD_FEDERATIVA,enf.NOM_ENTIDAD_FEDERATIVA "
			+ "FROM  REIPC_ENTIDAD_FEDERATIVA enf "
			+ "WHERE enf.ID_ENTIDAD_FEDERATIVA =?"
			+ "AND enf.STP_BAJA IS NULL ";
	
	public static final String QS_CONSULTA_ENTIDAD_FEDERATIVA = ""
			+ "SELECT enf.ID_ENTIDAD_FEDERATIVA,enf.NOM_ENTIDAD_FEDERATIVA "
			+ "FROM  REIPC_ENTIDAD_FEDERATIVA enf "
			+ "WHERE enf.STP_BAJA IS NULL ";
	
	public static final String QS_CONSULTA_ESCUELA_FILTROS = "SELECT "
			+ " CVE_ESCUELA, "
			+ " NOM_ESCUELA, NOM_CALLE, REF_NUMERO_INTERIOR, REF_NUMERO_EXTERIOR, "
			+ " NOM_COLONIA, REF_ENTIDAD_FEDERATIVA, REF_MUNICIPIO, CVE_CODIGO_POSTAL, REF_TURNO,  "
			+ " REF_TELEFONO "
			+ " FROM REIPC_ESCUELA "
			+ " WHERE STP_BAJA IS NULL AND UPPER(ID_ENTIDAD_FEDERATIVA) = UPPER(?) "
			+ " AND UPPER(CVE_MUNICIPIO) = UPPER(?) "
			+ " AND UPPER(CVE_LOCALIDAD) = UPPER(?) ";
	
	
	public static final String QS_CONSULTA_LOCALIDAD_EST_MUN =" SELECT "
			+ "c.ID_LOCALIDAD, c.NOM_LOCALIDAD, c.CVE_CODIGO_POSTAL, c.ID_ENTIDAD_FEDERATIVA, c.CVE_MUNICIPIO, c.CVE_LOCALIDAD "
			+ "FROM REIPC_LOCALIDAD c, REIPC_MUNICIPIO a,  REIPC_ENTIDAD_FEDERATIVA b "
			+ "WHERE c.ID_ENTIDAD_FEDERATIVA = a.ID_ENTIDAD_FEDERATIVA "
			+ "AND c.ID_ENTIDAD_FEDERATIVA = b.ID_ENTIDAD_FEDERATIVA "
			+ "AND c.CVE_MUNICIPIO=a.CVE_MUNICIPIO "
			+ "AND a.NOM_MUNICIPIO=UPPER(TRIM(?)) "
			+ "AND b.NOM_ENTIDAD_FEDERATIVA = UPPER(TRIM(?)) ";
	
}
